# Generated by Django 5.0.2 on 2024-03-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("username", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        max_length=150, primary_key=True, serialize=False
                    ),
                ),
                ("preferences", models.BooleanField(default=False)),
            ],
        ),
    ]
