# Generated by Django 5.0.2 on 2024-03-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=255)),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("non-vegetarian", "Non-vegetarian"),
                            ("vegan", "Vegan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("allergies", models.CharField(max_length=20)),
                ("height", models.PositiveIntegerField()),
                ("weight", models.PositiveIntegerField()),
                ("target_weight", models.PositiveIntegerField()),
                ("cuisines", models.ManyToManyField(to="users.cuisine")),
            ],
        ),
    ]
