# Generated by Django 5.0.2 on 2024-03-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_cuisine_userpreferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="userpreferences",
            name="allergies",
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="allergies",
            field=models.ManyToManyField(to="users.allergy"),
        ),
    ]
