# Generated by Django 5.0.2 on 2024-03-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_allergy_remove_userpreferences_allergies_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserPreferences",
        ),
    ]
