# Generated by Django 5.0.2 on 2024-03-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_userpreferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.customuser",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=255)),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("non-vegetarian", "Non-vegetarian"),
                            ("vegan", "Vegan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("height", models.PositiveIntegerField()),
                ("weight", models.PositiveIntegerField()),
                ("target_weight", models.PositiveIntegerField()),
                ("allergies", models.ManyToManyField(to="users.allergy")),
                ("cuisines", models.ManyToManyField(to="users.cuisine")),
            ],
        ),
    ]
