# Generated by Django 5.0.2 on 2024-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userpreferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="allergies",
            field=models.ManyToManyField(null=True, to="users.allergy"),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="cuisines",
            field=models.ManyToManyField(null=True, to="users.cuisine"),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="diet",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("non-vegetarian", "Non-vegetarian"),
                    ("vegan", "Vegan"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
