# Generated by Django 5.0.2 on 2024-03-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_userpreferences_allergies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
