# Generated by Django 5.0.2 on 2024-03-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_credentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="credentials",
        ),
    ]
