# Generated by Django 5.0.2 on 2024-04-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_usercalorie"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCalorie",
        ),
    ]
