# Generated by Django 5.0.2 on 2024-03-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_customuser_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="credentials",
            field=models.TextField(null=True),
        ),
    ]
