# Generated by Django 5.0.2 on 2024-04-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_customuser_credentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="credentials",
        ),
    ]
