# Generated by Django 5.0.2 on 2024-04-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_usercalorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercalorie",
            name="recipeId",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="usercalorie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.customuser"
            ),
        ),
    ]
