# Generated by Django 5.0.2 on 2024-03-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groceryStore", "0002_alter_orderitem_id_alter_userprofile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("iid", models.AutoField(primary_key=True, serialize=False)),
                ("iname", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField()),
            ],
        ),
    ]
