# Generated by Django 5.0.2 on 2024-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groceryStore", "0005_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="calories",
            field=models.IntegerField(default=0),
        ),
    ]
