# Generated by Django 5.0.2 on 2024-04-09 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groceryStore", "0007_remove_order_recipe_remove_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="grocery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="groceryStore.ingredient",
            ),
        ),
    ]
