# Generated by Django 5.0.2 on 2024-04-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groceryStore", "0008_alter_orderitem_grocery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("cancelled", "cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
