# Generated by Django 5.0.2 on 2024-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=150, primary_key=True, serialize=False
                    ),
                ),
                ("credentials", models.TextField(null=True)),
            ],
        ),
    ]
