# Generated by Django 5.0.2 on 2024-04-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userProfilePage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
